name: TrainTime - Pipeline

on:
  push:
    branches: ['**']
    paths:
      - 'TrainTimeServer/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: List files in TrainTimeServer
        run: ls -R ./TrainTimeServer

      - name: Restore dependencies
        run: dotnet restore TrainTime.csproj
        working-directory: ./TrainTimeServer

      - name: Build
        run: dotnet build TrainTime.csproj --no-restore
        working-directory: ./TrainTimeServer
